//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXON.Penny_JaroWinklerDistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class castObce
    {
        public Nullable<int> Kód_obce { get; set; }
        public string Název_části_obce { get; set; }
        public Nullable<int> PSČ { get; set; }
        public int P_Id { get; set; }
    }
}
