//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXON.Penny_JaroWinklerDistance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlexiCaptureEntities : DbContext
    {
        public FlexiCaptureEntities()
            : base("name=FlexiCaptureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SeznamKrestnichJmen> SeznamKrestnichJmen { get; set; }
        public DbSet<SeznamObci> SeznamObci { get; set; }
        public DbSet<SeznamPrijmeni> SeznamPrijmeni { get; set; }
        public DbSet<SeznamPSC> SeznamPSC { get; set; }
        public DbSet<SeznamTitulu> SeznamTitulu { get; set; }
        public DbSet<SeznamUlic> SeznamUlic { get; set; }
        public DbSet<Penny_A5_bw> Penny_A5_bw { get; set; }
    }
}
