//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXON.Penny_JaroWinklerDistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class obce
    {
        public string Název_obce { get; set; }
        public int Kód_obce { get; set; }
    
        public virtual obce obce1 { get; set; }
        public virtual obce obce2 { get; set; }
    }
}
