//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXON.Penny_JaroWinklerDistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penny_A5_bw
    {
        public string ID { get; set; }
        public string Titul { get; set; }
        public string Oslovení { get; set; }
        public string Jméno { get; set; }
        public Nullable<bool> JmenoNalezeno { get; set; }
        public string Příjmení { get; set; }
        public Nullable<bool> PrijmeniNalezeno { get; set; }
        public string Ulice { get; set; }
        public Nullable<bool> UliceNalezeno { get; set; }
        public string Číslo { get; set; }
        public string Město { get; set; }
        public Nullable<bool> MestoNalezeno { get; set; }
        public string PSČ { get; set; }
        public Nullable<bool> PscNalezeno { get; set; }
        public string Datum_narození { get; set; }
        public string Počet_osob_v_domácnosti { get; set; }
        public string Telefonní_číslo { get; set; }
        public string Email { get; set; }
        public string Název_dávky { get; set; }
        public string Zdroj_obrazu { get; set; }
        public string Exportovano { get; set; }
        public Nullable<bool> Overeno { get; set; }
        public string Kontrola_1 { get; set; }
        public string Kontrola_2 { get; set; }
        public string Kontrola_3 { get; set; }
        public string Čas_exportu_dokumentu { get; set; }
        public string Čas_poslední_úpravy_dokumentu { get; set; }
        public string Čas_rozpoznání_dokumentu { get; set; }
        public string Čas_vytvoření_dokumentu { get; set; }
        public string Číslo_dokumentu { get; set; }
        public string Poslední_editor_dokumentu { get; set; }
        public string Název_definice_dokumentu { get; set; }
        public string Počet_dokumentů_v_dávce { get; set; }
        public string Počet_neurčitých_znaků { get; set; }
        public string Počet_rozpoznaných_znaků { get; set; }
        public string Počet_stránek_dávky { get; set; }
        public string PAGE_IMAGES { get; set; }
        public string Pole_pro_typ_služby1 { get; set; }
        public string E_mail { get; set; }
        public string Kontrola_4 { get; set; }
        public string Kontrola_5 { get; set; }
        public string Kontrola_6 { get; set; }
        public bool Platnost { get; set; }
        public Nullable<bool> Processed { get; set; }
    }
}
